### PR TITLE
Change color scale to 0 - 1.0

### PR DESCRIPTION
**Pull request by aotmr**
Fixes issue #25

### CODE REVIEW

**Comment by jamestn529** [comment]
fixes issue #25

**Comment by newobj** [comment]
👍 Thanks. Would be great to get this merged. Is this library maintained any more though?

**Comment by aotmr** [comment]
Not if you go by last commit. From the look of it, issues have been piling up for a year. I'd do my best to maintain it, but I don't have an automated toolchain for releases. Does anyone have experience with automated Win32 builds?

**Comment by keharriso** [comment]
Thanks for the PR! Yeah, I've been away from maintaining this for quite a while, but I plan on updating to the latest LOVE and Nuklear versions some time. I'll try to stay on top of PRs as well in case anyone beats me to it.

**Pull request merged**
