### PR TITLE
MSVC tweaks

### PR DESCRIPTION
**Pull request by MikuAuahDark**
See #52 for CMake invocation instructions.

Let me know if there are more changes needed. Since I only modified this and perform build instruction at linked issue and it can load the sample demo without problems.

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
Using the simple example from the readme
gambar

**Comment by keharriso** [comment]
I'm not saying you're doing anything wrong, but personally I get this error message when I try to use the new dll:

error loading module 'nuklear' from file '.\nuklear.dll':
The specified procedure could not be found.

**Comment by MikuAuahDark** [comment]
Alright that's not actually a crash but error. From my understanding, crash is when the program just close without any Lua error message.

Anyway that error is caused because the changes from first commit of this pull request is not applied. I've added MSVC build instruction and opened the PR so you can review.

If you want to setup automated GitHub actions build (Linux and Windows), just let me know.

**Comment by keharriso** [comment]
I tried both x86 and x64 builds. Both of them crash. As in the window shows for a second or two then the window closes. I'm not sure what I'm doing differently.

If I could just get a confirmation from someone else that it's working for them, I'll merge the changes.

**Comment by MikuAuahDark** [comment]
Maybe you can setup a debugger to debug `nuklear.dll`? It's possible in VS by creating debug build, copying the debug DLL as usual, then on debugging options select "lovec.exe" as target executable.

If you don't know how to open the resulting project in VS, use `cmake --open build`.

**Comment by keharriso** [comment]
OK, so the example from the README works, but the included example in the example folder doesn't. I'll look into this a bit more and get back to you.

**Comment by keharriso** [comment]
The problem appears to be with "ui:layoutTemplateEnd()" in template.lua. Now to figure out exactly what the problem is.

**Comment by keharriso** [comment]
This keeps getting stranger and stranger. If I add in a print statement to `nk_love_layout_template_end`, the code stops crashing.

See below:

```c
static int nk_love_layout_template_end(lua_State *L)
{
	nk_love_assert_argc(lua_gettop(L) == 1);
	nk_love_assert_context(1);
	nk_layout_row_template_end(&context->nkctx);
	puts("nk_love_layout_template_end"); /* Stops crashing */
}
```

**Comment by keharriso** [comment]
Derp, I'm an idiot. That function needs to return something!

**Pull request merged**
